platform :ios, '12.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', { 'Debug' => :debug, 'Profile' => :release, 'Release' => :release }

def flutter_root
  g = File.expand_path(File.join('..','Flutter','Generated.xcconfig'), __FILE__)
  raise "#{g} must exist. Run 'flutter pub get' first." unless File.exist?(g)
  File.foreach(g){|l| m=l.match(/FLUTTER_ROOT\=(.*)/); return m[1].strip if m }
  raise "FLUTTER_ROOT not found."
end

require File.expand_path(File.join(flutter_root,'packages','flutter_tools','bin','podhelper.rb'))
flutter_ios_podfile_setup if defined?(flutter_ios_podfile_setup)
install! 'cocoapods', :generate_multiple_pod_projects => false

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
    end
  end
end
