name: Full Matrix Build (No Codesign IPA)

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  FLUTTER_VERSION: '3.3.8'
  FLUTTER_CHANNEL: 'stable'

jobs:
  linux-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache pub cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .fvm
          key: linux-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            linux-pub-

      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install FVM
        run: |
          dart --version
          dart pub global activate fvm
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          fvm --version

      - name: Setup Flutter via FVM
        run: |
          fvm install ${{ env.FLUTTER_VERSION }}
          fvm use ${{ env.FLUTTER_VERSION }} --force

      - name: Run full check suite (no iOS)
        env:
          SKIP_IOS_BUILD: "1"
          SKIP_WEB_BUILD: "1"
        run: |
          chmod +x tools/run-all-checks.sh
          ./tools/run-all-checks.sh --ci

      - name: Upload Android artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-release-artifacts
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/*.aab

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flutter-test-coverage
          path: coverage/

  ios-no-codesign:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Cache pub cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .fvm
          key: macos-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            macos-pub-

      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install FVM
        run: |
          dart --version
          dart pub global activate fvm
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          fvm --version

      - name: Setup Flutter via FVM
        run: |
          fvm install ${{ env.FLUTTER_VERSION }}
          fvm use ${{ env.FLUTTER_VERSION }} --force

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update

      - name: Run iOS build (no codesign)
        env:
          SKIP_ANDROID_BUILD: "1"
          SKIP_WEB_BUILD: "1"
        run: |
          chmod +x tools/run-all-checks.sh
          ./tools/run-all-checks.sh --ci

      - name: Upload IPA artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-no-codesign
          path: build/ios/ipa/*.ipa
