name: Debug Build (FVM 3.3.8 Fix)

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.3.8'
  FLUTTER_CHANNEL: 'stable'

jobs:
  android-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install FVM
        run: |
          dart --version
          dart pub global activate fvm
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          fvm --version

      - name: Setup Flutter via FVM
        run: fvm install ${{ env.FLUTTER_VERSION }}

      - name: Flutter pub get
        run: fvm flutter pub get

      - name: Build debug APK
        run: fvm flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  ios-debug:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install FVM
        run: |
          dart --version
          dart pub global activate fvm
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          fvm --version

      - name: Setup Flutter via FVM
        run: fvm install ${{ env.FLUTTER_VERSION }}

      - name: Flutter pub get
        run: fvm flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Build debug IPA (no signing)
        run: fvm flutter build ios --debug --no-codesign

      - name: Archive .app to .ipa
        run: |
          mkdir -p build/ios/ipa
          cd build/ios/iphonesimulator
          zip -r Runner-debug.ipa Runner.app

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-ipa
          path: build/ios/iphonesimulator/Runner-debug.ipa
