name: Debug build matrix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FLUTTER_VERSION: "3.3.8"
  JAVA_VERSION: "17"

jobs:
  prepare:
    name: Flutter analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
      - name: Pub get
        run: flutter pub get
      - name: Flutter analyze
        run: flutter analyze

  android-debug:
    name: Android debug APK
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
      - name: Pub get
        run: flutter pub get
      - name: Build debug APK
        run: flutter build apk --debug
      - uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  ios-debug:
    name: iOS debug (no codesign)
    runs-on: macos-13
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
      - name: Pub get
        run: flutter pub get
      - name: Build iOS debug
        run: flutter build ios --debug --no-codesign
      - uses: actions/upload-artifact@v4
        with:
          name: ios-debug-app
          path: build/ios/iphoneos/*.app

  windows-debug:
    name: Windows debug build
    runs-on: windows-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
      - name: Pub get
        shell: pwsh
        run: flutter pub get
      - name: Build Windows debug
        shell: pwsh
        run: flutter build windows --debug
      - uses: actions/upload-artifact@v4
        with:
          name: windows-debug-build
          path: build/windows/runner/Debug
