name: Flutter debug verification

on:
  push:
    branches:
      - main
      - work
  pull_request:
    branches:
      - main
      - work

env:
  FLUTTER_VERSION: "3.3.8"
  JAVA_VERSION: "17"

jobs:
  linux-quality:
    name: Analyze & test (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: flutter pub get
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      - name: Flutter test
        run: flutter test

  android-debug:
    name: Android debug APK
    runs-on: ubuntu-latest
    needs: linux-quality
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
            build/app/intermediates
          key: android-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            android-

      - name: flutter pub get
        run: flutter pub get

      - name: Flutter build apk --debug
        run: flutter build apk --debug

      - name: Upload Android debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  ios-debug:
    name: iOS debug (no codesign)
    runs-on: macos-13
    needs: linux-quality
    env:
      COCOAPODS_DISABLE_STATS: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Flutter precache iOS artifacts
        run: flutter precache --ios --no-web

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ios-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ios-

      - name: flutter pub get
        run: flutter pub get

      - name: Flutter build ios --debug --no-codesign
        run: flutter build ios --debug --no-codesign

      - name: Upload iOS debug app
        uses: actions/upload-artifact@v4
        with:
          name: ios-debug-app
          path: build/ios/iphoneos/*.app

  windows-debug:
    name: Windows debug build
    runs-on: windows-latest
    needs: linux-quality
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Enable Windows desktop
        shell: pwsh
        run: flutter config --enable-windows-desktop

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\Pub\Cache
            .dart_tool
          key: windows-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            windows-

      - name: flutter pub get
        shell: pwsh
        run: flutter pub get

      - name: Flutter build windows --debug
        shell: pwsh
        run: flutter build windows --debug

      - name: Upload Windows debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-debug-build
          path: build/windows/runner/Debug
