name: Release Builds

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ios:
    name: Build iOS Simulator
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.8"
      - name: Flutter Doctor
        run: flutter doctor -v
      - name: Flutter Analyze
        run: flutter analyze
      - name: Install CocoaPods
        working-directory: ios
        run: pod install
      - name: Build iOS Simulator
        run: flutter build ios --simulator --no-codesign

  android:
    name: Build Android Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.8"
      - name: Flutter Doctor
        run: flutter doctor -v
      - name: Flutter Analyze
        run: flutter analyze
      - name: Build Android APK
        run: flutter build apk --release

  windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.8"
      - name: Flutter Doctor
        run: flutter doctor -v
      - name: Flutter Analyze
        run: flutter analyze
      - name: Build Windows
        run: flutter build windows
